--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockHorizons/InvSee
branches:
- master
- "4.0"
projects:
  InvSee:
    path: ""
    icon: icon.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.3.2
        branch: "4.0"
...
